trinhngocthuyen/cocoapods-spm

lib/cocoapods-spm/hooks/spm_dependencies.rb
Instead of specifying like this `:requirement => { :kind => "exactVersion", :version => "0.0.1" }`, which is hard to remember, we can just specify `:version => "0.0.1"`.
Some shortcuts:
```rb
:version => "0.0.1"
:branch => "main"
:commit => "123abc"
```
=> FEAT: Some other ways to declare SPM package requirement

README.md, lib/cocoapods-spm/def/podfile.rb, lib/cocoapods-spm/def/spec.rb, lib/cocoapods-spm/def/spm_dependency.rb, lib/cocoapods-spm/def/spm_package.rb, lib/cocoapods-spm/def/target_definition.rb, lib/cocoapods-spm/def/xcodeproj.rb, lib/cocoapods-spm/dependencies_resolver.rb, lib/cocoapods-spm/hooks/base.rb, lib/cocoapods-spm/hooks/spm_dependencies.rb, lib/cocoapods-spm/main.rb
=> Update dependencies resolver

lib/cocoapods-spm/def/podfile.rb, lib/cocoapods-spm/hooks/post_integrate/update_embed_frameworks_script.rb, lib/cocoapods-spm/installer/analyzer.rb, lib/cocoapods-spm/main.rb, lib/cocoapods-spm/patch/aggregate_target.rb
Closes #20
Need to rethink about how to handle embedding frameworks & how those should be linked in the project
=> FIX: Missing dylib when running on devices

lib/cocoapods-spm/def/spm_package.rb
Allow option `:path` in `spm_pkg`, to make `spm_pkg` syntax similar to `pod` syntax.
=> Allow option `:path` in `spm_pkg`

lib/cocoapods-spm/installer/analyzer.rb, lib/cocoapods-spm/installer/validator.rb
Validate if there exists a package used as a dependency in podspec, but was not declared in Podfile.
=> FEAT: Validate missing pkgs

lib/cocoapods-spm/config.rb, lib/cocoapods-spm/config/pod.rb, lib/cocoapods-spm/config/project.rb, lib/cocoapods-spm/config/spm.rb, lib/cocoapods-spm/hooks/base.rb, lib/cocoapods-spm/hooks/post_integrate/2.resolve_pkg_deps.rb
Create symlink to package checkouts.
This way, we can cd to the symlink dir to dump package metadata.
=> Create symlink to package checkouts

examples/EX/SPMPackagePlayground.swift, examples/LocalPackages/debug-kit/Package.swift, examples/LocalPackages/debug-kit/Sources/DebugKit/DebugKit.swift, examples/Podfile, lib/cocoapods-spm/def/spm_package.rb, lib/cocoapods-spm/resolver/product_dep_resolver.rb, lib/cocoapods-spm/resolver/umbrella_package.rb
=> FIX: Cannot gen metadata b/c of wrong slug and local package

lib/cocoapods-spm/resolver/product_dep_resolver.rb
Fixes:
- Missing metadata in some cases. Previously, we did generate metadata for declared pkgs only. Now, all pkgs including their dependencies have their metadata generated.
- In the following declaration: [nearby#L180](https://github.com/google/nearby/blob/main/Package.swift#L189), the slug (instead of the package name) was used in the `package:` option.
```swift
.product(name: "AbseilCXX17", package: "abseil-cpp-SwiftPM")
```
In this case, we simply generate 2 different metadata files. One corresponds to the package name (ie. `AbseilCXX17`), the other corresponds to the package slug (ie. `abseil-cpp-SwiftPM`)
=> FIX: Missing metadata in some cases & handle metadata if using package slug in dependencies

examples/EX.xcodeproj/project.pbxproj, examples/EXTests/StaticResourcesTests.swift, examples/LocalPackages/debug-kit/Package.swift, examples/LocalPackages/debug-kit/Sources/DebugKit/Resources/DebugKit.trace, lib/cocoapods-spm/helpers/patch.rb, lib/cocoapods-spm/hooks/helpers/update_script.rb, lib/cocoapods-spm/hooks/post_integrate/6.update_embed_frameworks_script.rb, lib/cocoapods-spm/hooks/post_integrate/7.update_copy_resources_script.rb, lib/cocoapods-spm/patch/aggregate_target.rb, lib/cocoapods-spm/swift/package/resources.rb, lib/cocoapods-spm/swift/package/target.rb
=> FIX: Resources not copied

examples/LocalPackages/debug-kit/Package.swift, examples/LocalPackages/debug-kit/Sources/DebugKit/DebugKit.swift, examples/LocalPackages/debug-kit/Sources/DebugKitObjC/DebugKitObjC.m, examples/LocalPackages/debug-kit/Sources/DebugKitObjC/include/DebugKitObjC.h, lib/cocoapods-spm/swift/package/target.rb
Related: https://github.com/trinhngocthuyen/cocoapods-spm/issues/87#issuecomment-2115763572
=> FIX: Implicit public headers path

lib/cocoapods-spm/hooks/post_integrate/5.update_settings.rb, lib/cocoapods-spm/swift/package/description.rb, lib/cocoapods-spm/swift/package/target.rb
=> FIX: Firebase header paths not recognized

lib/cocoapods-spm/swift/package/target.rb
=> FIX: Implicit headers not found, causing missing modulemap

lib/cocoapods-spm/compatibility/all.rb, lib/cocoapods-spm/compatibility/rb26.rb, lib/cocoapods-spm/main.rb
=> Backward compatibility for ruby 2.6

examples/EX/SPMPackagePlayground.swift, examples/Podfile, examples/Podfile.lock, lib/cocoapods-spm/def/podfile.rb, lib/cocoapods-spm/resolver/recursive_target_resolver.rb, lib/cocoapods-spm/resolver/result.rb, lib/cocoapods-spm/swift/package/project_packages.rb, lib/cocoapods-spm/swift/package/target.rb
=> FIX: Conditional product dependencies were wrongly detected

.github/workflows/weekly-auto-deploy.yml
Add Github action to auto deploy (weekly basis) if there are associated PRs/issues of the current milestone.
=> CHORE: Github action: weekly auto deploy

.gitignore, CONTRIBUTING.md, Gemfile, Gemfile.lock, examples/LocalPods/CommonUI/CommonUI.podspec, examples/LocalPods/CommonUI/Sources/CommonUI.swift, examples/Podfile, examples/Podfile.lock, lib/cocoapods-spm/hooks/base.rb, lib/cocoapods-spm/hooks/post_integrate/1.add_spm_pkgs.rb
last PR have triggered github bug and hanging for many hours, as described by this link: https://github.com/orgs/community/discussions/78775
so I recreat this pr for fix issue #130 
and the last closed pr is there: #131 which contain some other bugs I reported in it's conversation, we can fix together
=> adjust to the Podfile generate_multiple_pod_projects=true mode

examples/EX/SPMPlayground.swift, examples/LocalPackages/ex-macros/Package.swift, examples/LocalPackages/ex-macros/Sources/Wizard/Wizard.swift, examples/LocalPackages/ex-macros/Sources/WizardImpl/HexColorMacro.swift, examples/LocalPackages/ex-macros/Sources/WizardImpl/WizardImpl.swift, examples/LocalPackages/ex-macros/Sources/WizardPlayground/main.swift, examples/Makefile, examples/Podfile, examples/Podfile.lock, lib/cocoapods-spm/config/spm.rb, lib/cocoapods-spm/def/podfile.rb, lib/cocoapods-spm/macro/fetcher.rb, lib/cocoapods-spm/macro/pod_installer.rb
=> FEAT: Support local macro pod

lib/cocoapods-spm/macro/config.rb, lib/cocoapods-spm/macro/prebuilder.rb
=> FEAT: Shared macro cache to speed up macro prebuild

README.md, docs/declaring_packages.md, lib/cocoapods-spm/def/spm_package.rb
=> FEAT: Support requirement upToNextMajorVersion/upToNextMinorVersion/versionRange

examples/Podfile, lib/cocoapods-spm/resolver/umbrella_package.rb
=> FIX: Corrupted umbrella pkg with upToNextMajor/upToNextMinor/versionRange

examples/LocalPods/CommonUI/CommonUI.podspec, examples/LocalPods/CommonUI/Sources/CommonUI.swift, examples/Podfile, lib/cocoapods-spm/hooks/post_integrate/05.update_settings.rb
=> FIX: Add implicit headers in pods build dir

docs/README.md, docs/using-with-xcodebuild.md, lib/cocoapods-spm/hooks/post_integrate/05.update_settings.rb
=> FIX: SourcePackages dir in case of archive

examples/EXTests/EXTests.swift, examples/LocalPackages/core-utils/Package.swift, examples/LocalPackages/core-utils/Sources/TestKit/TestKit.swift, examples/LocalPods/Services/Services.podspec, examples/Podfile, lib/cocoapods-spm/resolver/target_dep_resolver.rb
=> FIX: Exclude test specs #166
